### PR TITLE
Unit F and initial BGA footprint

### PR DESCRIPTION
**Pull request by angst7**
I think the .1" pin length might be a bit short for the length of the pin numbers.  But that's the standard, so I went with it.  The footprint could definitely use a second set of eyes.

### CODE REVIEW

**Comment by alexanderhiam** [comment]
Darn, good point about the pin length, those are long names! Since there's still a few units to go, rather than going through and changing all the lengths I might take a whack at using [KiPart](https://github.com/xesscorp/KiPart) to generate the symbol instead...

**Comment by alexanderhiam** [comment]
Here's unit A ready for KiPart: https://github.com/graycatlabs/OSD335x-KiCad/blob/kipart/OSD3358-kipart.csv

I think this is probably the way to go, and it'll be a lot less work if we realize something is terribly wrong later and have to start over!

**Comment by angst7** [comment]
Ok, that looks good.  I've never used KiPart, I'll take a look.  Incidentally, why the tilde (~) instead of pin numbers?

**Comment by alexanderhiam** [comment]
tilde is the way to leave out a pin number in kicad. I'm just getting all the names in first, then I was going to go through and add the pin numbers all at once - in Eagle you have to open that separate pin association window to see it, so it just seemed more efficient this way.

**Comment by angst7** [comment]
Oh, I see.  I just created the Unit F for KiPart, but I converted the info from the .csv that Octavo has on the part page.  Took no time at all.  It's at http://octavosystems.com/octavosystems.com/wp-content/uploads/2016/05/OSD3358-BAS_OrCAD_Symbol.xlsx

**Comment by alexanderhiam** [comment]
Oh wow! I hadn't seen that spreadsheet, that sure makes life easier...

**Comment by alexanderhiam** [comment]
OK, just generated the entire part from that OrCAD spreadsheet. It's broken up into a lot more units than the Eagle part, and I think I might like it better. What do you think? (kipart branch -> OSD3358.lib)

**Comment by angst7** [comment]
Yeah, I was following the eagle part, but thats a lot of unnecessary work.  Lets just use what they provide.

**Pull request merged**
